project:
  type: website
  output-dir: docs

website:
  title: "PSTC 1340: Principles & Methods of GIS"
  page-footer: "© Rachel Franklin · CC BY 4.0 · Third-party images under fair use"

format:
  html:
    theme: [default, site_style.scss]